In [7]:
import pandas as pd
import numpy as np
job_data_to_load = "dice_us_tech_original.csv"
job_data = pd.read_csv(job_data_to_load)

In [8]:
# drop unneeded columns
del job_data["advertiserurl"]
del job_data["jobid"]
del job_data["postdate"]
del job_data["shift"]
del job_data["uniq_id"]

# # split joblocation_address into city and state
new=job_data["joblocation_address"].str.split(",",n=1,expand=True)
job_data["Loc_state"]=new[1]
job_data["Loc_city"]=new[0]
del job_data["joblocation_address"]
# drop rows where required fields are empty
job_data = job_data.loc[job_data.Loc_state.notnull()]
job_data = job_data.loc[job_data.company.notnull()]
 
# Remove listings for Canadian states
job_data = job_data.loc[~job_data.Loc_state.str.contains("ON")]
job_data = job_data.loc[~job_data.Loc_state.str.contains("BC")]

# replace all links in site_name column with dice.com
job_data.loc[:,"site_name"] = "dice.com"
# add empty columns for Skills
job_data["Skills"] = np.nan
# rename columns to prep for merging with other datasets
job_data = job_data.rename(columns={"company":"Company","jobdescription":"Description","jobtitle":"Position",
                                    "employmenttype_jobstatus":"Type","site_name":"Source"})
# rearrange columns
job_data = job_data[["Position","Company","Description","Loc_state","Loc_city","Skills","Type","Source"]]
job_data.head(10)

,Position,Company,Description,Loc_state,Loc_city,Skills,Type,Source
0,AUTOMATION TEST ENGINEER,"Digital Intelligence Systems, LLC",Looking for Selenium engineers...must have sol...,GA,Atlanta,NaN,"C2H Corp-To-Corp, C2H Independent, C2H W2, 3 M...",dice.com
1,Information Security Engineer,University of Chicago/IT Services,The University of Chicago has a rapidly growin...,IL,Chicago,NaN,Full Time,dice.com
2,Business Solutions Architect,"Galaxy Systems, Inc.","GalaxE.SolutionsEvery day, our solutions affec...",IL,Schaumburg,NaN,Full Time,dice.com
3,"Java Developer (mid level)- FT- GREAT culture,...",TransTech LLC,Java DeveloperFull-time/direct-hireBolingbrook...,IL,Bolingbrook,NaN,Full Time,dice.com
4,DevOps Engineer,Matrix Resources,Midtown based high tech firm has an immediate ...,GA,Atlanta,NaN,Full Time,dice.com
5,SAP FICO Architect,Yash Technologies,We are looking for a Senior SAP FICO Architect...,IL,Chicago,NaN,"Full Time, Permanant",dice.com
6,Network Engineer,Noble1,Network Engineer Job Description A Network Eng...,GA,Atlanta,NaN,"Full Time, Direct Hire",dice.com
7,Sr. Web Application Developer (Cloud Team) - C...,"Bluebeam Software, Inc.",Bluebeam is looking for talented sr. web devel...,IL,Chicago,NaN,"Full Time, Full Time",dice.com
8,Front End Developer,Genesis10,This is a fulltime position for a Javascript d...,NY,New York,NaN,"Full Time, Direct Placement",dice.com
9,Application Support Engineer,"VanderHouwen & Associates, Inc.",SummaryOur client is the leading provider of o...,WA,Seattle,NaN,"C2H W2, Contract to hire",dice.com

In [9]:
job_data.count()

Position       21850
Company        21850
Description    21850
Loc_state      21850
Loc_city       21850
Skills             0
Type           21624
Source         21850
dtype: int64

In [10]:
Keywords = ["Data Scien", "Data Analy", "Data Eng", "Business Intelligence", "Tableau", "VBA", "Python", "JSON", "NumPy",  "Pandas", "Matplotlib", "Beautiful Soap", "Statistics Modeling", "API", "SQL", "MongoDB", "ETL", "HTML", "CSS", "JavaScript", "AJAX", "D3", "Leaflet", "Hadoop", "Machine Learning", "Product Analyst", "BI Analyst"]

filtered_job_data = job_data[job_data["Position"].str.contains("|".join(Keywords))]
filtered_job_data.to_csv("Dice_US_Tech_FilteredJobData.csv")
filtered_job_data.count()

Position       1566
Company        1566
Description    1566
Loc_state      1566
Loc_city       1566
Skills            0
Type           1556
Source         1566
dtype: int64